spring:
   jpa.hibernate.ddl-auto : update
   datasource.url : jdbc:mysql://localhost:3306/rsweb
   datasource.username : root
   datasource.password : ravi
   datasource.driver-class-name : com.mysql.jdbc.Driver