spring:

#http://localhost:8080/swagger-ui/index.html
   jpa.hibernate.ddl-auto: update
   datasource:   
       url: jdbc:mysql://localhost:3306/rsweb
       username: root
       password: root
       driver-class-name : com.mysql.jdbc.Driver